### ISSUE TITLE
Create "Register" view

### ISSUE THREAD

**Issue by jeberdugo** [jeberdugo/AndesSaves-iOS-Grupo_25#2]
According to UI prototype https://www.figma.com/proto/scbr9mfEfBK7amgwjfVHgV/Untitled?type=design&node-id=0-1&t=xV9EUWSERgrwY7Av-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=148%3A2

**Comment by Sebastian643829** [comment]
Now, it is working
